apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: app-claim1
  name: app-claim1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  #volumeName: "k8s-py-sample-pv-1-volume"
