apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-py-sample-pv-0-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: app-claim0
  hostPath:
    path: "/app/app_test/config"

