apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-py-sample-pv-db-0-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: db-claim0
  hostPath:
    path: "/app/app_test/data"